'use strict';
const fullName = 'Tiffany Brown';
const isCool = true;
const totalPets = 1;
console.log('Full Name:', fullName);
console.log('Cool?', isCool);
console.log('Total # of Pets:', totalPets);
console.log('Data Type of Full Name:', typeof fullName);
console.log('Data Type of isCool:', typeof isCool);
console.log('Data Type of totalPets:', typeof totalPets);
const empty = null;
console.log('Empty:', empty);
console.log('Data Type of empty:', typeof empty);
let nothing;
console.log('Nothing:', nothing);
console.log('Data Type of Nothing:', typeof nothing);
