'use strict';
const colors = ['red', 'white', 'blue'];
console.log('Value of colors[0]:', colors[0]);
console.log('Value of colors[1]:', colors[1]);
console.log('Value of colors[2]:', colors[2]);
console.log(`America is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`);
colors[2] = 'green';
console.log(`Mexico is ${colors[0]}, ${colors[1]}, and ${colors[2]}.`);
console.log('The value of the colors array:', colors);
console.log('The Data Type of the colors array:', typeof colors);
const students = ['Glenn', 'Rick', 'Carol', 'Maggie'];
const numberOfStudents = students.length;
console.log(`There are ${numberOfStudents} students in the class.`);
const lastIndex = numberOfStudents - 1;
const lastStudent = students[lastIndex];
console.log(`The last student in the array is ${lastStudent}.`);
console.log('The value of the students array:', students);
console.log('The data type of the students array:', typeof students);
