'use strict';
const width = 5;
const height = 8;
const area = width * height;
console.log('Value of Area: ', area);
console.log('Data Type of Area: ', typeof area);
const bill = 75;
const payment = 125;
const change = payment - bill;
console.log('Amount of Change: ', change);
console.log('Data Type of Change: ', typeof change);
const quizzes = 15;
const midterm = 25;
const final = 50;
const grade = (quizzes + midterm + final) / 3;
console.log('Value of grade: ', grade);
console.log('Data Type of Grade: ', typeof grade);
const firstName = 'Tiffany';
const lastName = 'Brown';
const fullName = firstName + ' ' + lastName;
console.log('Value of fullName: ', fullName);
console.log('Data Type of fullName: ', typeof fullName);
const pH = 8;
const isAcidic = pH > 7;
console.log('Value of isAcidic: ', isAcidic);
console.log('Data Type of isAcidic: ', typeof isAcidic);
const headCount = 322;
const isSparta = headCount === 300;
console.log('The value of isSparta: ', isSparta);
console.log('Data Type of isSparta: ', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT';
console.log('The value of motto: ', motto);
console.log('The Data Type of motto: ', typeof motto);
